[build]
  publish = "public"
  command = "yarn build"
  functions = "lambda"
  
[build.environment]
  YARN_VERSION = "1.17.0"
  YARN_FLAGS = "--no-ignore-optional"

[[plugins]]
package = "netlify-plugin-gatsby-cache"