backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: "guitars"
    label: "Guitar"
    folder: "src/pages/guitars"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Slug", name: "slug"}
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "guitar-page"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: Guitar Image, name: "guitarImages", widget: list, field: {label: Image, name: image, widget: image}}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "pages"
    label: "Pages"
    files:
      - label: "Homepage"
        file: "src/pages/index.md"
        name: "index"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden"}
          - {label: Heading, name: heading, widget: string}
          - label: "Gallery Item"
            name: "galleryItems"
            widget: "list"
            fields:
              - {label: Image, name: image, widget: image}
              - {label: URL, name: url, widget: text}
